### ISSUE TITLE
Exception when selecting objects for 3d view too fast

### ISSUE THREAD

**Issue by constantinpape** [platybrowser/mmb-fiji#71]
When volume rendering is activated for a segmentation and several objects are selected in sequence "too fast" the following exception is thrown:
```
Exception in thread "Thread-44" java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1442)
	at java.util.HashMap$KeyIterator.next(HashMap.java:1466)
	at de.embl.cba.tables.view.Segments3dView.showSelectedSegments(Segments3dView.java:265)
	at de.embl.cba.tables.view.Segments3dView.updateAndShowSelectedSegments(Segments3dView.java:240)
	at de.embl.cba.tables.view.Segments3dView.access$100(Segments3dView.java:37)
	at de.embl.cba.tables.view.Segments3dView$1.selectionChanged(Segments3dView.java:206)
	at de.embl.cba.tables.select.DefaultSelectionModel.lambda$notifySelectionListeners$0(DefaultSelectionModel.java:64)
	at java.lang.Thread.run(Thread.java:748)
```
Here "too fast" means, that the next object is selected before the previous one has been fully rendered. Probably there is a lock missing somewhere ...

**Comment by tischi** [comment]
I was iterating through a `Set` that could be modified. I think I fixed it now...
Pleas try tomorrow.

**Comment by constantinpape** [comment]
Fixed now.
